Added error messages in case something goes wrong.

diff --git a/yt-dashload b/yt-dashload
--- a/yt-dashload
+++ b/yt-dashload
@@ -37,10 +37,10 @@ command -v ffmpeg >/dev/null 2>&1 || fatal "Please install ffmpeg."
 URL="$1"
 echo "URL: $URL"
 
-VIDEO_ID=$(./youtube-dl --get-id "$URL")
+VIDEO_ID=$(./youtube-dl --get-id "$URL") || fatal "Error fetching metadata."
 echo "VideoID: $VIDEO_ID"
 
-VIDEO_TITLE=$(./youtube-dl -e "$URL")
+VIDEO_TITLE=$(./youtube-dl -e "$URL") || fatal "Error fetching metadata."
 echo "Title: $VIDEO_TITLE"
 
 # Video
@@ -58,7 +58,7 @@ echo "Title: $VIDEO_TITLE"
 echo "Downloading video..."
 
 TMP_VIDEO="tmp.video.$VIDEO_ID"
-./youtube-dl -f 137/136/135/134/133/160 -o "$TMP_VIDEO" "$URL"
+./youtube-dl -f 137/136/135/134/133/160 -o "$TMP_VIDEO" "$URL" || fatal "Download error."
 
 # Audio
 
@@ -69,11 +69,14 @@ TMP_VIDEO="tmp.video.$VIDEO_ID"
 echo "Downloading audio..."
 
 TMP_AUDIO="tmp.audio.$VIDEO_ID"
-./youtube-dl -f 140/171 -o "$TMP_AUDIO" "$URL"
+./youtube-dl -f 140/171 -o "$TMP_AUDIO" "$URL" || fatal "Download error"
 
 # Merge video and audio
 
-ffmpeg -i "$TMP_VIDEO" -i "$TMP_AUDIO" -c copy file:"$VIDEO_TITLE.mp4"
+ffmpeg -i "$TMP_VIDEO" -i "$TMP_AUDIO" -c copy file:"$VIDEO_TITLE.mp4" || {
+	rm "$VIDEO_TITLE.mp4" 2> /dev/null
+	fatal "Conversion error."
+}
 
 # Cleanup
 
